#!/usr/bin/env python3

import sys
import os
import cgi
from html import escape

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from database.database import Database

db = Database.load_state()

# Create instance of FieldStorage
form = cgi.FieldStorage()

def handle_new_link(new_link: str) -> None:
    '''
    Adds a new link to be displayed.

    Keyword arguments:
    new_link -- link to be added to the display
    '''
    db.add_record(new_link)

    # Pre-database implementation
    # with open('../course-links.txt', 'a') as file:
    #     file.write(f'{new_link.strip()}\n')

def delete_link(link_to_delete: int) -> None:
    '''
    Removes link from list of links and link storage.

    Does not execute if link_to_delete is not positive or out of range of links.

    Keyword arguments:
    link_to_delete -- index of link to be deleted (0-indexed)
    '''
    db.delete_record(link_to_delete)

    # Pre database implementation
    # if (link_to_delete <= 0 or link_to_delete > len(links)):
    #     raise IndexError()

    # links.pop(link_to_delete - 1)

    # # Store links to be kept back into file
    # with open('../course-links.txt', 'w') as file:
    #     for link in links:
    #         file.write(f'{link}\n')

# Pre database implementation
# def list_links() -> List[str]:
#     '''Returns a list of all links.'''
#     links = []
#     with open('../course-links.txt', 'r') as file:
#         for link in file:
#             link = link.strip()
#             if link:
#                 links.append(link)
#     return links

# Get data from fields
new_link = form.getvalue('new-link')

if new_link:
    handle_new_link(new_link)

# Pre database implementation
# links = list_links()

if form.getvalue('delete'):
    try:
        link_to_delete = int(form.getvalue('link-to-delete'))
        delete_link(link_to_delete)
    except Exception:
        # Act as no deletion
        pass

# Print HTML response
print("Content-Type: text/html\r\n\r\n")
print("<html>")
print("<body>")
print("<h1>Course Links</h1>")

# Display form
print('''
    <form action="input-links" method="post">
        <label for="new-link">Enter Course Link:</label>
        <input type="text" id="new-link" name="new-link"><br><br>
        <input type="submit" value="Submit">
    </form>
''')

# Display links
for i, link in enumerate(db.list_records()):
    escaped_link = escape(link)
    print(f'''
        <p>
            Link {i + 1}: <a href=\'{escaped_link}\'>{escaped_link}</a>
            <form action='input-links' method='post'>
                <input type='hidden' name='link-to-delete' value='{i}'>
                <input type='submit' value='Delete' name='delete'>
            </form>
        </p>
    ''')

print("</body>")
print("</html>")